//lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBITS0FGTiP-g0aaIoCQ55Lh_TUGlRa8zg',
    appId: '1:386925733059:web:badbe2d908b55dc19c6e76',
    messagingSenderId: '386925733059',
    projectId: 'rwws-5ecbb',
    authDomain: 'rwws-5ecbb.firebaseapp.com',
    storageBucket: 'rwws-5ecbb.firebasestorage.app',
    measurementId: 'G-LLRLZJSSFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLnx4uwVKRJXWIpbc9R-9tsNQlpK8YIIk',
    appId: '1:386925733059:android:24111ef30373ddb09c6e76',
    messagingSenderId: '386925733059',
    projectId: 'rwws-5ecbb',
    storageBucket: 'rwws-5ecbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm23GjuTVr8iec0bILlr044vy85ig8-LE',
    appId: '1:386925733059:ios:3b7fe065cd3f1f069c6e76',
    messagingSenderId: '386925733059',
    projectId: 'rwws-5ecbb',
    storageBucket: 'rwws-5ecbb.firebasestorage.app',
    iosClientId: '386925733059-io8u8aeibd57njtf89dbsk8lblt4ecc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinchain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm23GjuTVr8iec0bILlr044vy85ig8-LE',
    appId: '1:386925733059:ios:3b7fe065cd3f1f069c6e76',
    messagingSenderId: '386925733059',
    projectId: 'rwws-5ecbb',
    storageBucket: 'rwws-5ecbb.firebasestorage.app',
    iosClientId: '386925733059-io8u8aeibd57njtf89dbsk8lblt4ecc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinchain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBITS0FGTiP-g0aaIoCQ55Lh_TUGlRa8zg',
    appId: '1:386925733059:web:69dffb25b6e0364c9c6e76',
    messagingSenderId: '386925733059',
    projectId: 'rwws-5ecbb',
    authDomain: 'rwws-5ecbb.firebaseapp.com',
    storageBucket: 'rwws-5ecbb.firebasestorage.app',
    measurementId: 'G-7NSW3470WZ',
  );
}
